import { Builder } from '../../gameBuilder/builder';
import { MapHandler } from '../../gameBuilder/mapHandler';
import { AutoHeal } from '../../gameLogic/commands/autoHeal';
import { Equipment } from '../../gameLogic/inventory/equipment';
import { Inventory } from '../../gameLogic/inventory/inventory';
import { EventCategory, LogMessage } from '../../gameLogic/messages/logMessage';
import { MessageLog } from '../../gameLogic/messages/messageLog';
import { Mob } from '../../gameLogic/mobs/mob';
import { NeedsHandler } from '../../gameLogic/needs/needsHandler';
import { Stats } from '../../gameLogic/stats/stats';
import { RandomGenerator } from '../../randomGenerator/randomGenerator';
import { GameMapType } from '../gameLogic/maps/mapModel/gameMapType';
import { MobAI } from '../gameLogic/mobs/mobAI';

export type GameState = {
  rand: RandomGenerator;
  player: Mob;
  ai: MobAI | null;
  log: MessageLog;
  dungeon: MapHandler;
  build: Builder;
  autoHeal: AutoHeal | undefined;
  inventory: Inventory | undefined;
  equipment: Equipment | undefined;
  needs: NeedsHandler | undefined;
  stats: Stats;
  surfaceTemp: number;
  shouldShowStoryScreen: boolean;
  shownStoryLevels: number[];
  currentMap(): GameMapType | null;
  message(msg: LogMessage): void;
  flash(msg: LogMessage): void;
  addCurrentEvent(evt: EventCategory): void;
};
